invoked "continue" outside of a loop
    while executing
"continue"
    (file "./error/InvalidContinue.tcl" line 4)
